In [1]:
from custom_dataset import Censius2FahrenheitDataset
from torch.utils.data import DataLoader

dataset = Censius2FahrenheitDataset(is_train=False)
dataloader = DataLoader(dataset, batch_size=3, shuffle=True)

for celsius, fahrenheit in dataloader:
    print(celsius, fahrenheit)


tensor([-47.9980,  -1.9520, -27.9780], dtype=torch.float64) tensor([-54.3964,  28.4865, -18.3604], dtype=torch.float64)
tensor([-17.9680, -37.9880,   2.0521], dtype=torch.float64) tensor([ -0.3423, -36.3784,  35.6937], dtype=torch.float64)
tensor([-20.9710,  16.0661,  37.0871], dtype=torch.float64) tensor([-5.7477, 60.9189, 98.7568], dtype=torch.float64)
tensor([-14.9650,   0.0501,  41.0911], dtype=torch.float64) tensor([  5.0631,  32.0901, 105.9640], dtype=torch.float64)
tensor([ 19.0691, -24.9750,  27.0771], dtype=torch.float64) tensor([ 66.3243, -12.9550,  80.7387], dtype=torch.float64)
tensor([  5.0551, -38.9890, -18.9690], dtype=torch.float64) tensor([ 41.0991, -38.1802,  -2.1441], dtype=torch.float64)
tensor([18.0681, 30.0801,  6.0561], dtype=torch.float64) tensor([64.5225, 86.1441, 42.9009], dtype=torch.float64)
tensor([48.0981, 31.0811, 23.0731], dtype=torch.float64) tensor([118.5766,  87.9459,  73.5315], dtype=torch.float64)
tensor([  3.0531, -36.9870, -45.9960], dtype=torch.f